package com.bank.bian.financialcrimemodels;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Financial Crime Models
 *
 * Business Area:      Risk and Compliance
 * Business Domain:    Financial Crime
 * Functional Pattern: Develop
 * Asset Type:         Financial Crime Model
 * Control Record:     Financial Crime Model Development Project
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Financial Crime Models — BIAN Semantic API")
                .description("Service Domain 'Financial Crime Models' (Develop pattern) "
                        + "operating on the 'Financial Crime Model Development Project' control record.")
                .version("0.1.0"));
    }
}
